### ISSUE TITLE
Incorrect number of parameters on method SendRequestSynchronous

### ISSUE THREAD

**Issue by Loredani68** [SchneiderInfosystems/FB4D#38] opened 2020-03-25 10:18 UTC
The number of parameters of method call "SendRequestSynchronous" (e.g. line 85 in the library FB4D.OAuth.pas) does not match the defined number of parameters.
For this reason none of the sample projects can be compiled.

To reproduce the error, simply compile the test project "Intro".
[dcc32 Fehler] FB4D.OAuth.pas(86): E2250 Es gibt keine überladene Version von 'SendRequestSynchronous', die man mit diesen Argumenten aufrufen kann

**Comment by ChristophSchneiderTrihow** [comment] 2020-03-26 07:20
I cannot reproduce this issue and the entire FB4DSample project is compilable. 
In the class TFirebaseRequest of unit TB4D.Request.pas there are two overloaded methods of  SendRequestSynchronous. In FB4D.OAuth.pas the first overloaded method  TFirebaseRequest.SendRequestSynchronous of line 427 (TB4D.Request.pas) will be used.

Please check if you have fetched the current version of the source (commit cf68bb6eaf1179183172cf13537c4645eff078db). Please close this issue as soon as you can compile or deliver more information to reproduce.

**Comment by SchneiderInfosystems** [comment] 2020-03-26 07:22
I cannot reproduce this issue and the entire FB4DSample project is compilable.
In the class TFirebaseRequest of unit TB4D.Request.pas there are two overloaded methods of SendRequestSynchronous. In FB4D.OAuth.pas the first overloaded method TFirebaseRequest.SendRequestSynchronous of line 427 (TB4D.Request.pas) will be used.

Please check if you have fetched the current version of the source (commit cf68bb6). Please close this issue as soon as you can compile or deliver more information to reproduce.

**Comment by Loredani68** [comment] 2020-03-26 10:26
I am using the current version and the installation went absolutely smoothly.

That's very strange.
When I move the mouse over the 'SendRequestSynchronous' call, the declaration info shows me the definition of the second overloaded method (with 6 parameters). And when I jump to the declaration using the context menu, I logically end up in the second overloaded method.

But if I change the declaration of the two methods in the class definition of TFirebaseRequest the first overloaded method (with 5 parameters) is shown and jumped to respectively.
But when compiling the error occurs anyway.

I use Delphi 10.3 Update 1.
I have asked a colleague with the same configuration to download the project and test DemoFB4D. He also gets the same error.

Is there any other hint?

**Comment by SchneiderInfosystems** [comment] 2020-03-26 13:04
This issue is related to Delphi 10.3.1. Please check this issue https://github.com/SchneiderInfosystems/FB4D/issues/29

**Closed by SchneiderInfosystems** 2020-03-26 13:04 UTC
Labels: question

**Comment by SchneiderInfosystems** [comment] 2020-03-27 07:43
I have added a remark to De 10.3.1 in the project readme file:
https://github.com/SchneiderInfosystems/FB4D/blob/master/README.md#hint-delphi-103-update-1-is-not-longer-supported-because-of-an-issue-in-the-rtl

**Comment by Loredani68** [comment] 2020-03-27 08:44
All right. I have now installed version 10.3.3 and everything works fine.
Thank you very much for your great work.
